import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')??'',SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'',ANON=Deno.env.get('SUPABASE_ANON_KEY')??'';
const CLIENT_ID=(Deno.env.get('MERCADOPAGO_CLIENT_ID')??'').trim(),CLIENT_SECRET=(Deno.env.get('MERCADOPAGO_CLIENT_SECRET')??'').trim();
const PUBLIC_URL='https://m-commerce-ar.vercel.app',LEGACY_PUBLIC_URL='https://j3-plataform.vercel.app',OAUTH_CALLBACK=`${SUPABASE_URL}/functions/v1/mercadopago-connect`,PROVIDER='mercadopago';
function b64url(b:Uint8Array){return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha256(s:string){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}
function random(n=48){return b64url(crypto.getRandomValues(new Uint8Array(n)))}
function cors(req:Request){const o=req.headers.get('origin');const allowed=o===PUBLIC_URL||o===LEGACY_PUBLIC_URL;return {'Access-Control-Allow-Origin':allowed?o:PUBLIC_URL,'Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Vary':'Origin'}}
function json(req:Request,b:unknown,status=200){return new Response(JSON.stringify(b),{status,headers:{...cors(req),'content-type':'application/json','cache-control':'no-store'}})}
function validUuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
async function authUser(req:Request){const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))throw new Error('AUTH_REQUIRED');const c=createClient(SUPABASE_URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const {data:{user},error}=await c.auth.getUser();if(error||!user)throw new Error('AUTH_REQUIRED');return {user,client:c}}
async function isMaster(c:any,id:string){const {data,error}=await c.from('profiles').select('role').eq('id',id).maybeSingle();if(error)throw error;return data?.role==='admin'}
async function canManageSite(admin:any,userId:string,siteId:string,master:boolean){if(master)return true;const {data,error}=await admin.from('site_memberships').select('role').eq('site_id',siteId).eq('user_id',userId).eq('status','active').maybeSingle();if(error)throw error;return data?.role==='merchant_owner'}
async function billingAccount(admin:any){const {data,error}=await admin.from('platform_billing_accounts').select('*').eq('provider',PROVIDER).maybeSingle();if(error)throw error;return data}
async function collectorToken(admin:any){const a=await billingAccount(admin);if(!a||a.status!=='connected')throw new Error('J3_BILLING_ACCOUNT_NOT_CONNECTED');const exp=a.expires_at?new Date(a.expires_at).getTime():Number.MAX_SAFE_INTEGER;if(exp>Date.now()+10*60_000||!a.refresh_token)return a.access_token;if(!CLIENT_ID||!CLIENT_SECRET)return a.access_token;const r=await fetch('https://api.mercadopago.com/oauth/token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:'refresh_token',refresh_token:a.refresh_token})});const f=await r.json().catch(()=>({}));if(!r.ok||!f?.access_token)throw new Error('J3_BILLING_TOKEN_REFRESH_FAILED');await admin.from('platform_billing_accounts').update({access_token:f.access_token,refresh_token:f.refresh_token||a.refresh_token,scope:f.scope||a.scope,expires_at:f.expires_in?new Date(Date.now()+Number(f.expires_in)*1000).toISOString():a.expires_at,status:'connected',updated_at:new Date().toISOString()}).eq('provider',PROVIDER);return f.access_token}
async function syncPreapproval(admin:any,siteId:string,token:string,preId:string){const r=await fetch(`https://api.mercadopago.com/preapproval/${encodeURIComponent(preId)}`,{headers:{authorization:`Bearer ${token}`}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error('SUBSCRIPTION_LOOKUP_FAILED');if(String(p.external_reference||'')!==siteId)throw new Error('SUBSCRIPTION_SITE_MISMATCH');const ps=String(p.status||'pending'),next=p.next_payment_date||null,mapped=ps==='authorized'?'active':(ps==='cancelled'||ps==='canceled')?'cancelled':ps==='paused'?'past_due':ps==='pending'?'pending':'past_due';await admin.from('site_subscriptions').update({provider:PROVIDER,provider_subscription_id:String(p.id||preId),provider_status:ps,provider_init_point:p.init_point||null,provider_payer_email:p.payer_email||undefined,provider_next_payment_at:next,next_due_at:next||undefined,status:mapped,billing_mode:'auto',updated_at:new Date().toISOString()}).eq('site_id',siteId);if(ps==='authorized')await admin.from('sites').update({subscription_status:'active',is_suspended:false,updated_at:new Date().toISOString()}).eq('id',siteId);if(ps==='cancelled'||ps==='canceled')await admin.from('sites').update({subscription_status:'cancelled',updated_at:new Date().toISOString()}).eq('id',siteId);return p}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return json(req,{error:'METHOD_NOT_ALLOWED'},405);const admin=createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false}});try{const {user,client}=await authUser(req),master=await isMaster(client,user.id),body=await req.json().catch(()=>({})),action=String(body.action||'');
 if(['account_status','account_start','account_disconnect'].includes(action))return json(req,{error:'USE_J3_BILLING_ACCOUNT'},410)
 if(action==='commission_payout'){if(!master)throw new Error('ADMIN_REQUIRED');const sid=String(body.salesperson_id||'');if(!validUuid(sid))throw new Error('INVALID_SALESPERSON');const {data,error}=await client.rpc('platform_create_salesperson_payout',{p_salesperson_id:sid,p_reference:String(body.reference||'')});if(error)throw error;return json(req,data)}
 const siteId=String(body.site_id||'');if(!validUuid(siteId))throw new Error('INVALID_SITE');if(!(await canManageSite(admin,user.id,siteId,master)))throw new Error('OWNER_REQUIRED');
 if(action==='subscription_create'){const token=await collectorToken(admin);const {data:site,error:sErr}=await admin.from('sites').select('id,name,product_tier').eq('id',siteId).maybeSingle();if(sErr||!site)throw new Error('SITE_NOT_FOUND');const {data:sub,error:subErr}=await admin.from('site_subscriptions').select('*,subscription_plans(monthly_price,name)').eq('site_id',siteId).maybeSingle();if(subErr||!sub)throw new Error('SUBSCRIPTION_NOT_CONFIGURED');const amount=Number(sub.amount_override??sub.subscription_plans?.monthly_price??0);if(!(amount>0))throw new Error('INVALID_SUBSCRIPTION_AMOUNT');if(sub.provider_subscription_id&&['pending','authorized','paused'].includes(String(sub.provider_status||''))){const p=await syncPreapproval(admin,siteId,token,String(sub.provider_subscription_id));return json(req,{ok:true,provider_status:p.status,checkout_url:p.init_point||sub.provider_init_point||null,subscription_id:p.id})}const payer=String(master?(body.payer_email||''):(user.email||sub.provider_payer_email||'')).trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(payer))throw new Error(master?'PAYER_EMAIL_REQUIRED_FOR_MASTER':'PAYER_EMAIL_REQUIRED');const payload={reason:`M Commerce · ${String(site.name).slice(0,80)}`,external_reference:siteId,payer_email:payer,auto_recurring:{frequency:1,frequency_type:'months',transaction_amount:Number(amount.toFixed(2)),currency_id:'ARS'},back_url:`${PUBLIC_URL}${site.product_tier==='simple'?'/simple/app':'/app-comercio/panel'}?billing_return=1&site=${encodeURIComponent(siteId)}`,status:'pending'};const r=await fetch('https://api.mercadopago.com/preapproval',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','x-idempotency-key':`j3-sub-${siteId}-${crypto.randomUUID()}`},body:JSON.stringify(payload)});const p=await r.json().catch(()=>({}));if(!r.ok||!p?.id||!p?.init_point)throw new Error(`SUBSCRIPTION_CREATE_FAILED:${p?.message||r.status}`);const upd=await admin.from('site_subscriptions').update({billing_mode:'auto',provider:PROVIDER,provider_subscription_id:String(p.id),provider_status:String(p.status||'pending'),provider_init_point:String(p.init_point),provider_payer_email:payer,provider_next_payment_at:p.next_payment_date||null,updated_at:new Date().toISOString()}).eq('site_id',siteId);if(upd.error)throw upd.error;await admin.from('subscription_events').insert({site_id:siteId,event_type:'auto_subscription_created',amount,provider:PROVIDER,provider_reference:String(p.id),detail:{payer_email:payer,status:p.status||'pending'}});return json(req,{ok:true,provider_status:p.status||'pending',checkout_url:p.init_point,subscription_id:p.id})}
 if(action==='subscription_refresh'){const token=await collectorToken(admin);const {data:sub,error}=await admin.from('site_subscriptions').select('provider_subscription_id').eq('site_id',siteId).maybeSingle();if(error||!sub?.provider_subscription_id)throw new Error('SUBSCRIPTION_NOT_LINKED');const p=await syncPreapproval(admin,siteId,token,String(sub.provider_subscription_id));return json(req,{ok:true,status:p.status,next_payment_date:p.next_payment_date||null,checkout_url:p.init_point||null})}
 if(action==='subscription_cancel'){if(!master)throw new Error('ADMIN_REQUIRED');const token=await collectorToken(admin);const {data:sub,error}=await admin.from('site_subscriptions').select('provider_subscription_id').eq('site_id',siteId).maybeSingle();if(error||!sub?.provider_subscription_id)throw new Error('SUBSCRIPTION_NOT_LINKED');const r=await fetch(`https://api.mercadopago.com/preapproval/${encodeURIComponent(sub.provider_subscription_id)}`,{method:'PUT',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({status:'cancelled'})});if(!r.ok)throw new Error('SUBSCRIPTION_CANCEL_FAILED');const p=await syncPreapproval(admin,siteId,token,String(sub.provider_subscription_id));return json(req,{ok:true,status:p.status||'cancelled'})}
 return json(req,{error:'INVALID_ACTION'},422)}catch(e){const raw=e instanceof Error?e.message:String((e as any)?.message||(e as any)?.code||'');const known=/^[A-Z0-9_]+(?::[A-Z0-9_]+)?$/.test(raw)?raw:'INTERNAL_ERROR';console.error(JSON.stringify({event:'j3_billing_error',code:known,request_id:crypto.randomUUID()}));return json(req,{error:known,message:known},known==='AUTH_REQUIRED'?401:(known==='ADMIN_REQUIRED'||known==='OWNER_REQUIRED')?403:400)}});
